# USER VARIABLES
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export XDG_DATA_DIRS="$XDG_DATA_DIRS:$HOME/.local/share"

path+="$HOME/.local/bin"
path+="$HOME/.luarocks/bin"
path+="$HOME/.local/share/gem/ruby/3.0.0/bin"

# Save zsh history
export HISTFILE="$ZDOTDIR/.zhistory"    
export HISTSIZE=10000                   
export SAVEHIST=10000                   

export EDITOR="nvim"
export VISUAL="nvim"
