unset LC_MESSAGES
source /etc/locale.conf

if [[ $- != *i* ]]; then
    return
fi

source $ZDOTDIR/store.zsh
source $ZDOTDIR/aliases.zsh

setopt MENU_COMPLETE ALWAYS_TO_END
setopt HIST_SAVE_NO_DUPS
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

# PLUGINS
source "$ZDOTDIR/ls_colours"
source "$ZDOTDIR/zoxide"
# This must be before compinit
zmodload zsh/complist
autoload -U compinit promptinit
compinit
promptinit

# Help command
autoload -Uz run-help;
(( ${+aliases[run-help]} )) && unalias run-help
alias help=run-help
autoload -Uz run-help-git run-help-ip run-help-openssl run-help-p4 run-help-sudo run-help-svk run-help-svn

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Case insensitive completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion::complete:*' gain-privileges 1
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME:-$HOME/.cache/}/zsh/.zcompcache"
zstyle ':completion:*' menu select interactive search 
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' group-name ''

_comp_options+=(globdots)

export KEYTIMEOUT=1

# VIM mod
source $ZDOTDIR/'cursor_mode'

source "$ZDOTDIR/prompt"


# Load other keybindings
source "$ZDOTDIR/bindings"
source "$ZDOTDIR/prompt_name"
source "$ZDOTDIR/direnv"

if [ "$DESKTOP_SESSION" != "gnome" ]
then
    export MOZ_ENABLE_WAYLAND=1
fi

if [[ "$IS_NIX" = 1 ]]; then
    remove_profile() {
        if [[ $# -lt 1 ]]; then
            return 0
        fi
        profile=$(nix profile list | rg -i "$1" | cut -d' ' -f 1)
        if [[ -z $profile ]]; then
            echo  "No matching package found for '$1'"
            return -1
        fi
        nix profile remove $profile
        shift
        $0 "$@"
    }
fi

# Start gnome keyring
# if [ -n "$DESKTOP_SESSION" ];then
#     eval $(gnome-keyring-daemon --start)
#     export SSH_AUTH_SOCK
# fi
