unset LC_MESSAGES
source /etc/locale.conf

if [[ $- != *i* ]]; then
    return
fi

# quck function to source scripts from zsh folder
function import() {
    if [[ $# -eq 0 ]]; then
        return
    fi
    source "$ZDOTDIR/$1"
    shift
    import $@
}

# holds important functionality for other parts
import store.zsh

import aliases.zsh

# PLUGINS
import etc.zsh zoxide.zsh direnv.zsh cursor_mode.zsh bindings.zsh prompt.zsh prompt_name.zsh 

source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
