PROMPT='%F{#ff0055}%n%f@%F{#dd6}%m%f: %~> '

# PLUGINS
source "$ZDOTDIR/ls_colours"
source "$ZDOTDIR/zoxide"
# This must be before compinit
zmodload zsh/complist
# Case insensitive completion
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
autoload -U compinit; compinit
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

zstyle ':completion:*' completer _extensions _complete _approximate
zstyle ':completion:*' squeeze-slashes true
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path "${XDG_CACHE_HOME:-$HOME/.cache/}/zsh/.zcompcache"
zstyle ':completion:*' menu select interactive search 
zstyle ':completion:*:*:*:*:descriptions' format '%F{green}-- %d --%f'
zstyle ':completion:*:messages' format ' %F{purple} -- %d --%f'
zstyle ':completion:*:warnings' format ' %F{red}-- no matches found --%f'
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' group-name ''

_comp_options+=(globdots)

setopt MENU_COMPLETE ALWAYS_TO_END
setopt HIST_SAVE_NO_DUPS
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

# VIM mod
source $ZDOTDIR/'cursor_mode'
export KEYTIMEOUT=1
# Load other keybindings
source "$ZDOTDIR/bindings"

# Command aliases
alias ls="exa"
alias la="exa -la"
alias search="pacman -Ss"
alias install="sudo pacman -Syu"
alias reload="source $ZDOTDIR/.zshrc"

# Start gnome keyring
if [ -e "$DESKTOP_SESSION" ];then
    eval $(gnome-keyring-daemon --start)
    export SSH_AUTH_SOCK
fi
