# USER VARIABLES
if [[ $(uname -s) == 'Darwin' ]]; then
	export IS_MAC=1
fi

if [[ $IS_MAC -eq 1 ]]; then
    export XDG_CONFIG_HOME="$HOME/Library/Preferences/"
    export XDG_DATA_HOME="$HOME/Library/"
    export XDG_CACHE_HOME="$HOME/Library/Caches/"
    export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
else
    export XDG_CONFIG_HOME="$HOME/.config"
    export XDG_DATA_HOME="$HOME/.local/share"
    export XDG_CACHE_HOME="$HOME/.cache"
    export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
    export XDG_DATA_DIRS="$XDG_DATA_DIRS:$HOME/.local/share"
fi

path+="$HOME/.local/bin"
path+="$HOME/.luarocks/bin"
path+="$HOME/.local/share/gem/ruby/3.0.0/bin"
path+="$HOME/Applications/"

# Save zsh history
export HISTFILE="$ZDOTDIR/.zhistory"    
export HISTSIZE=10000                   
export SAVEHIST=10000                   

export EDITOR="nvim"
export VISUAL="nvim"

# Stuff to prevent $HOME cluttering
export ATOM_HOME="$XDG_DATA_HOME"/atom
export CABAL_CONFIG="$XDG_CONFIG_HOME"/cabal/config
export CABAL_DIR="$XDG_CACHE_HOME"/cabal
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export GOPATH="$XDG_DATA_HOME"/go
export GRADLE_USER_HOME="$XDG_DATA_HOME"/gradle
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export KDEHOME="$XDG_CONFIG_HOME"/kde
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export NUGET_PACKAGES="$XDG_CACHE_HOME"/NuGetPackages
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

path+="$CARGO_HOME/bin"

[[ -n "$IS_MAC" ]] && . "$CARGO_HOME/env"
