typeset -a _missing
unset LC_MESSAGES
source /etc/locale.conf

# quck function to source scripts from zsh folder
function import() {
    if [[ $# -eq 0 ]]; then
        return
    fi
    source "$ZDOTDIR/$1"
    shift
    import $@
}

autoload -U add-zsh-hook

function meta::join() {
    local sep=$1
    shift
    eval "print \${(j.${sep}.)@}"
}

function meta::osc() {
    if [[ $# -eq 0 ]]; then
        print 'fail to osc' args: $@
    fi
    print -Pn "\e]$(meta::join ';' $@)\e\\"
}

function meta::osc7() {
    meta::osc 7 "file://$PWD"
}

# PLUGINS
import etc.zsh zoxide.zsh direnv.zsh cursor_mode.zsh
import bindings.zsh prompt.zsh prompt_name.zsh aliases.zsh


add-zsh-hook chpwd meta::osc7

if [[ -f /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]]; then
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
else
    _missing+='zsh-syntax-highlighting'
fi

if [[ ${#_missing} -ge 0 ]]; then
    echo "There are parts missing from your installation. They are:"
    for x in $_missing; do
        echo -e '    -' $x
    done
fi
