theme = "onedark"

[editor]
color-modes = true
line-number = "relative"

    [editor.cursor-shape]
    insert = "bar"
    normal = "block"
    select = "underline"

    [editor.indent-guides]
    render = true

    [editor.lsp]
    display-inlay-hints = true
    display-messages = true

    [editor.statusline]
    right = [ "workspace-diagnostics", "file-type", "version-control" ]

        [editor.statusline.mode]
        insert = "INSERT"
        normal = "NORMAL"
        select = "SELECT"

[keys.insert]
C-space = "completion"

[keys.normal]
"$" = "goto_line_end"
A-H = "swap_view_left"
A-J = "swap_view_down"
A-K = "swap_view_up"
A-L = "swap_view_right"
A-h = "jump_view_left"
A-i = "vsplit"
A-j = "jump_view_down"
A-k = "jump_view_up"
A-l = "jump_view_right"
A-o = "hsplit"
C = [ "select_mode", "goto_line_end", "change_selection" ]
C-r = "redo"
C-space = "buffer_picker"
D = [ "select_mode", "goto_line_end", "delete_selection" ]
G = "goto_last_line"
K = "hover"
S = "select_regex"
V = [ "select_mode", "extend_to_line_bounds" ]
Y = [ "select_mode", "goto_line_end", "yank", "exit_select_mode", "collapse_selection" ]
_ = "goto_line_start"
esc = "collapse_selection"
s = "change_selection"
x = "extend_to_line_bounds"
"|" = "goto_line_start"

    [keys.normal.g]
    U = "switch_to_uppercase"
    u = "switch_to_lowercase"

        [keys.normal.g.c]
        c = "toggle_comments"

    [keys.normal.q]
    q = "match_brackets"

    [keys.normal.space]
    space = "file_picker_in_current_directory"

        [keys.normal.space.c]
        a = "code_action"

[keys.select]
"$" = "goto_line_end"
G = "goto_last_line"
_ = "goto_line_start"
s = "change_selection"
"|" = "goto_line_start"

    [keys.select.g]
    U = "switch_to_uppercase"
    u = "switch_to_lowercase"

    [keys.select.q]
    q = "match_brackets"